version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: cig_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: SntCont

  backend:
    build: ./backend
    container_name: cig_backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/SntCont
    volumes:
      - ./data/exports:/data/exports
      - ./logs:/app/logs
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: cig_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
